f=open("D:\DE\Python\Tutorials\Lectures\demo.txt","r")
# data=f.read()
line1=f.readline()
print(line1)
line2=f.readline()
print(line2)
# f.close()

# data=f.write("Overwrite file content using write")
# print(data)